[package]
name = "shishua_rs"
version = "0.1.1"
authors = ["Dario Bartussek <d.bartussek@gmail.com>", "Sean McNamara <smcnam@gmail.com>"]
edition = "2021"

[dependencies]
packed_simd = { version = "0.3.6", package = "packed_simd_2" }
rand_core = "0"
byteorder = "1"
