[package]
name = "shishua_rs"
version = "0.1.1"
authors = ["Dario Bartussek <d.bartussek@gmail.com>", "Sean McNamara <smcnam@gmail.com>"]
edition = "2021"

[dependencies]
packed_simd_2 = { git = "https://github.com/rust-lang/packed_simd" }
rand_core = "0"
byteorder = "1"
